# Generated by Django 2.2.10 on 2020-05-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_news_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_active', '-data']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-is_active', 'name']},
        ),
    ]
